
--BIRT SQL query

select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER AS "Order Number", 
	CLASSICMODELS.ORDERS.ORDERDATE AS "Order Date",
	CLASSICMODELS.ORDERDETAILS.PRODUCTCODE AS "Product Code",
	CLASSICMODELS.PRODUCTS.PRODUCTNAME AS "Product Name",
	CLASSICMODELS.PRODUCTS.BUYPRICE AS "Product Price",
	CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED AS "Order Quantity"
from CLASSICMODELS.ORDERDETAILS 
join CLASSICMODELS.ORDERS
on CLASSICMODELS.ORDERDETAILS.ORDERNUMBER = CLASSICMODELS.ORDERS.ORDERNUMBER
join CLASSICMODELS.PRODUCTS
on CLASSICMODELS.ORDERDETAILS.PRODUCTCODE = CLASSICMODELS.PRODUCTS.PRODUCTCODE
where CLASSICMODELS.ORDERS.ORDERDATE between '2011-02-06' and '2011-02-24'